services:
  - name: selenium-flask-api
    type: web
    runtime: docker
    region: oregon
    plan: hobby  # Use the 'hobby' plan for free tier
    dockerfilePath: Dockerfile  # The path to the Dockerfile
    buildCommand: ""  # Docker-based services don't need a separate build command
    startCommand: ""  # Docker-based services use CMD defined in the Dockerfile
    envVars:
      - key: PORT
        value: 5000
    healthCheckPath: /
    scaling:
      minInstances: 1
      maxInstances: 1  # For Hobby plan, you can use only one instance
