services:
  - name: selenium-flask-api
    type: web
    runtime: docker
    region: oregon
    plan: free  # Use 'free' plan (previously named 'hobby')
    dockerfilePath: Dockerfile  # The path to the Dockerfile
    buildCommand: ""  # Docker-based services don't need a separate build command
    startCommand: ""  # Docker-based services use CMD defined in the Dockerfile
    envVars:
      - key: PORT
        value: 5000
    healthCheckPath: /health
